name: Bygg og publiser bibliotek
on:
  push:
    branches:
      - main
    paths:
      - 'lib/src/main/**'

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'

      - name: Bygg bibliotek
        run:  ./gradlew build

      - name: Push tag
        run: |
          VERSION_NAME="$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(git log -1 --pretty='%h')"
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          git tag $VERSION_NAME
          git push origin $VERSION_NAME

      - name: Publish packages
        run: gradle -Plib_version="${{ env.VERSION_NAME }}" publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
